  os: linux
  dist: focal
  arch: arm64-graviton2
  virt: lxd
  group: edge

  jobs:
    include:
      - language: smalltalk
        before_install:
          - "sudo apt-get install libpulse0"
        smalltalk_vm:
          - Squeak-5.0
        smalltalk:
          - Squeak64-trunk          
