  os: linux
  dist: focal
  arch: arm64-graviton2
  virt: lxd
  group: edge

  jobs:
    include:
      - language: smalltalk
        before_install:
          - "sudo dpkg --add-architecture i386"
          - "sudo apt-get update"
          - "sudo apt-get dist-upgrade"
          - "sudo apt-get install libpulse0"
          - "sudo apt-get install libpulse0:i386"
        smalltalk_vm:
          - Squeak-5.0
        smalltalk:
          - Squeak64-trunk
          
