os: linux
dist: bionic

jobs:
  include:
    
    - services: 
      - elasticsearch
      script:
      - systemctl status elasticsearch
      - sleep 5
      - curl 127.0.0.1:9200
 
    - services: 
      - elasticsearch
      script:
      - systemctl status elasticsearch
      - sleep 4
      - curl 127.0.0.1:9200
      
