os: linux
dist: focal
services:
  - mongodb 
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - mongo test --eval "printjson(db.getCollectionNames())"
